services:
  discord-music:
    build:
      context: ../../../../..
      dockerfile: src/bundle/pods/pods/discord-music/Dockerfile
    image: thebundle/discord-music:local
    container_name: thebundle-discord-music
    restart: unless-stopped
    init: true
    tty: true
    cap_add:
      - SYS_NICE
    network_mode: "host"
    env_file:
      - path: .discord.env
        required: true
