services:
  website:
    build:
      context: ../../../../..
      dockerfile: src/bundle/pods/pods/website/Dockerfile
    image: thebundle/website:local
    container_name: thebundle-website
    restart: unless-stopped
    tty: true
    ports:
      - "8000:8000"
