from typing import List, Optional

from example_module.shape import Circle, Shape, Square, Triangle

def wrap_shapes(shapes: list[Shape]) -> float: ...
def maybe_make_circle(flag: bool) -> Circle | None: ...
def maybe_make_square(flag: bool) -> Square | None: ...
def maybe_make_triangle(flag: bool) -> Triangle | None: ...

class CompositeShape(Shape):
    def __init__(self) -> None: ...
    def add(self, s: Shape) -> None: ...
    def area(self) -> float: ...

def make_composite() -> CompositeShape: ...
