name: windows 🪟

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  windows_tests:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-test
        with:
          python-version: ${{ matrix.python-version }}
